function figure1 = plot_all_resid(YMatrix1)

%this plots the residual tests for all the sessions and also the mean over
%the sessions

% NOTE number of sessions hardcoded in here

%CREATEFIGURE(YMATRIX1)
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 27-Jan-2009 12:59:08

% Create figure
figure1 = figure('XVisual','0x24 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)','PaperSize',[20.98 29.68],'Visible','off');

% Create axes
axes1 = axes('Parent',figure1,'XTick',[1 2 3 4 5 6 7 8 9 10 11]);
% Uncomment the following line to preserve the X-limits of the axes
% xlim([1 11]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Color',[0.8039 0.8784 0.9686],'Parent',axes1);
set(plot1(size(YMatrix1,2)-1),'Marker','o','LineWidth',2,'Color',[1 0 0]);
set(plot1(size(YMatrix1,2)),'LineStyle','--','Color',[0 0 1]);

