function figure1 = createfigure1(YMatrix1, YMatrix2,config)
%CREATEFIGURE1(YMATRIX1,YMATRIX2)
%  YMATRIX1:  matrix of y data
%  YMATRIX2:  matrix of y data

%  Auto-generated by MATLAB on 02-Sep-2009 22:10:16

% Create figure
figure1 = figure('XVisual','0x24 (TrueColor, depth 24, RGB mask 0xff0000 0xff00 0x00ff)','PaperType','a4letter',...
    'PaperSize',[20.98 29.68]);


% Create subplot
subplot1 = subplot(2,1,1,'Parent',figure1,'XTickLabel',{'0','1','2','3','4','5','6','7','8','9','10','11'},...
    'XTick',[1 2 3 4 5 6 7 8 9 10 11 12]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim([1 12]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot1 = plot(YMatrix1,'Parent',subplot1);
if size(YMatrix1,2) == 3
    set(plot1(1),'DisplayName','nmf pronation');
    set(plot1(2),'DisplayName','90 %');
    set(plot1(3),'DisplayName','pcaica pronation');
else
    set(plot1(1),'DisplayName','nmf pronation');
    set(plot1(2),'DisplayName','nmf supination');
    set(plot1(3),'DisplayName','nmf pro sup');
    set(plot1(4),'DisplayName','90 %');
    set(plot1(5),'DisplayName','pcaica pronation');
    set(plot1(6),'DisplayName','pcaica supination');
    set(plot1(7),'DisplayName','pcaica pro sup');
end


% Create xlabel
xlabel('model order');

% Create ylabel
ylabel('remaining error');

% Create title
title('residual test of data');

% Create subplot
subplot2 = subplot(2,1,2,'Parent',figure1,'XTickLabel',{'0','1','2','3','4','5','6','7','8','9','10','11'},...
    'XTick',[1 2 3 4 5 6 7 8 9 10 11 12]);
% Uncomment the following line to preserve the X-limits of the axes
 xlim([1 12]);
box('on');
hold('all');

% Create multiple lines using matrix input to plot
plot2 = plot(YMatrix2,'Parent',subplot2);
if size(YMatrix2,2) == 3
    set(plot1(1),'DisplayName','nmf pronation');
    set(plot1(2),'DisplayName','90 %');
    set(plot1(3),'DisplayName','pcaica pronation');
else
    set(plot2(1),'DisplayName','nmf pronation');
    set(plot2(2),'DisplayName','nmf supination');
    set(plot2(3),'DisplayName','nmf pro sup');
    set(plot2(4),'DisplayName','90 %');
    set(plot2(5),'DisplayName','pcaica pronation');
    set(plot2(6),'DisplayName','pcaica supination');
    set(plot2(7),'DisplayName','pcaica pro sup');
end

% Create xlabel
xlabel('model order');

% Create ylabel
ylabel('remaining error');

% Create title
title('residual test of shuffled data');

% Create legend
legend(subplot2,'show');

% Create legend
legend(subplot1,'show');


